import { Metadata } from "next";

export const metadata: Metadata = {
  title: {
    absolute: "",
    default: "Next.js",
    template: "%s | Next.js",
  },
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header style={{ backgroundColor: "lightblue", padding: "1rem" }}>
          <p>Header</p>
        </header>
        {children}
        <footer style={{ backgroundColor: "ghostwhite", padding: "1rem" }}>
          <p>
            Lorem, ipsum dolor sit amet consectetur adipisicing elit. Nesciunt
            aut at, adipisci laudantium dignissimos sed eum tempora nisi
            explicabo quam. Nobis id corporis reiciendis explicabo! Repellendus
            quisquam ut voluptas hic!
          </p>
        </footer>
      </body>
    </html>
  );
}
