import { Metadata } from "next";

export const metadata: Metadata = {
  title: {
    absolute: "Blog"
  },
  description: "Generated by Next.js",
};

const Blog = () => {
  return <div>Blog</div>;
};

export default Blog;
