import { Metadata } from "next";

export const metadata: Metadata = {
  title: {
    absolute: "Blog",
  },
  description: "Generated by Next.js",
};

const Blog = () => {
  return <h1>My Blog</h1>;
};

export default Blog;
